### PR TITLE
a/b test preferMSE option for Mux Player

### PR DESCRIPTION
**Pull request by dylanjha**
exp_2022-09-06_14-48-01

### CODE REVIEW

**Comment by dylanjha** [comment]
We're gonna see how Mux Data performance metrics look in Safari Desktop browsers (the only place where this setting really matters)

**Comment by gkatsev** [comment]
Could apply on ipads as well (technically android as well, but that's always MSE as of latest mux player)

**Review by jaredsmith — APPROVED** [review]
Looks good to me.  Just out of curiosity, any reason to set it this way vs. using a cookie (like we did for the dynamic chunk size), to make it easier to troubleshoot?  I'm assuming you're really only looking at overall aggregated performance?

**Comment by dylanjha** [comment]
@jaredsmith good q!

No particular reason besides this was the easiest/quickest and I didn't want to bother adding another cookie key.

If the user refreshes and gets the different behavior it's okay for our experiment and yes we'll just be filtering Mux Data by Desktop Safari and segmenting by this `experiment_name`

**Pull request merged**
