### PR TITLE
Specify Video Only

### PR DESCRIPTION
**Pull request by sampoder**
Hi, so when I used my Galaxy A51 smartphone I opened up the site and clicked add a video and one of the options was to use the camera. But when I clicked on the camera it, only let me take a photo oof. 

This PR might fix that, but honestly it's untested. So I'll go test it when I get a deploy preview. Thanks!

### CODE REVIEW

**Comment by sampoder** [comment]
oh yikes, a team member needs to accept.... well maybe this will fix it?

**Comment by sampoder** [comment]
really cool project btw! I used mux once and it confused me how to add a video

**Comment by dylanjha** [comment]
@sampoder thanks! I just approved the deployment -- can you give it a try?

**Comment by GeneticGenesis** [comment]
Would this stop an audio-only recording work? 

Do audio only recordings work today?

**Comment by dylanjha** [comment]
FWIW I have seen problems with this `accept="video/*"` being super inconsistent across browsers. If I remember with that attribute Safari does not accept mp4s.

I think theres a work around for that, which is more like `accept="video/mp4,video/x-m4v,video/*"`- but I'm a little worried there might be problems there too and other types of video files will be excluded.

Ideally:

- I would like to keep the input as broad as possible, allow for any file types and rely on Mux to error out the asset if it's not a video file

**Comment by GeneticGenesis** [comment]
Answer: No, audio only streams don't work today anyway 😅

**Comment by sampoder** [comment]
I'll go test it

**Comment by sampoder** [comment]
lol it didn't help

**Comment by sampoder** [comment]
big brain phone was just like, hmmm no video well no camera then

**Comment by dylanjha** [comment]
Confirmed that with this change and clicking "Upload video" Safari does not show mp4s as selectable from the filesystem (Go figure!).

Thanks @sampoder I'll see if I can find a work around for Galaxy A51 smartphone

**Comment by sampoder** [comment]
oof safari is a weird browser

**Comment by sampoder** [comment]
lol I accidentally closed this, but I mean it probs can be closed

**Pull request closed without merging**
